version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn main:app --bind 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker
    restart: always
    ports:
      - "500:5000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`host.docker.internal`)
      - traefik.http.services.app.loadbalancer.server.port=500
      - traefik.http.routers.app-http.entrypoints=http
    volumes:
      - fx_temp:/home/app/web/tmp

  traefik:
    image: traefik:2.9.1
    ports:
      - "8080:500"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
      - traefik-public-certificates:/certificates

volumes:
  traefik-public-certificates:
  fx_temp:
    driver: local
